version: 0.2
phases:
  install:
    commands:
      - npm install -g aws-cdk
      - npm i -g aws-cdk --force # maybe updates it?
      - cdk --version
  pre_build:
    commands:
      - cd stepfunctions
      - pip install -r requirements.txt
      - cdk bootstrap aws://319713307186/us-east-1 --cloudformation-execution-policies arn:aws:iam::aws:policy/AdministratorAccess aws://319713307186/us-east-1
  build:
    commands:
      - cdk deploy --require-approval never aws-stepfunctions-integ
